# Generated by Django 4.2.3 on 2023-07-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_phone'),
    ]

    operations = [
    ]
